# site settings
title: Innovate Trent
# subtitle:
email: innovate@trentu.ca
description: "We're a group of students at Trent University dedicated to making exciting ideas become reality!"
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://innovate.trentu.info" # the base hostname & protocol for your site
author: Innovate Trent
# street_address: 1234 Somewhere Road
city: Peterborough
province: Ontario
# zip_code: 55555
country: Canada
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
# 500px_url:
facebook_url: https://www.facebook.com/groups/350257192197862/
github_url: https://github.com/trent-innovate
# gitlab_url: https://gitlab.com/u/andrewbanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

highlighter: rouge

sass:
  style: compressed
 
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
